workflows:
  android-workflow:
    name: ToTV+ Ultimate Fix Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      # نستخدم القناة المستقرة ونترك السيرفر يختار أحدث نسخة stable
      flutter: stable
      java: 17
    scripts:
      - name: Force Flutter Stable
        script: |
          # هذا السطر يضمن أننا لسنا على نسخة Master المعطوبة
          flutter channel stable
          flutter upgrade --force
          flutter doctor

      - name: Clean Build Environment
        script: |
          flutter clean
          rm -rf android/.gradle
          rm -f android/local.properties

      - name: Setup Android Files
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          # إجبار إعدادات الذاكرة لـ Kotlin
          cat <<EOF > android/gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx4G
          kotlin.code.style=official
          EOF

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build APK (Release)
        script: |
          # سنستخدم build apk بدلاً من bundle لتجنب تعقيدات الـ bundle الحالية
          flutter build apk --release --no-pub --target-platform android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
