workflows:
  android-workflow:
    name: ToTV+ Stable Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      # نضع نسخة مستقرة هنا
      flutter: 3.24.5 
      java: 17
    scripts:
      - name: Force Fix Flutter Tools
        script: |
          # الانتقال للقناة المستقرة وحذف أي ملفات تالفة في أدوات فلاتر
          flutter channel stable
          flutter upgrade --force
          flutter doctor

      - name: Clean and Setup
        script: |
          flutter clean
          rm -rf android/.gradle
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          # إعدادات الذاكرة لـ Kotlin
          cat <<EOF > android/gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx4G
          EOF

      - name: Build APK
        script: |
          flutter pub get
          # بناء APK بدلاً من Bundle لتجنب الخطأ في FlutterPlugin.kt
          flutter build apk --release --no-pub --target-platform android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-haedirasso@gmail.com
