workflows:
  android-workflow:
    name: ToTV+ Stable Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      # تثبيت نسخة فلاتر مستقرة (3.24.5) يحل مشكلة Unresolved reference نهائياً
      flutter: 3.24.5
      java: 17
    scripts:
      - name: Clean and Prepare
        script: | 
          flutter clean
          # حذف أي ملفات قد تسبب تضارب
          rm -f android/local.properties
          
      - name: Auto-generate missing files
        script: |
          # إنشاء ملف التعريفات الأساسي
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          # تفعيل AndroidX بشكل إجباري
          cat <<EOF > android/gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx4G
          EOF

      - name: Install dependencies
        script: | 
          flutter pub get

      - name: Build Android APK
        script: | 
          # بناء APK بدلاً من Bundle لضمان التشغيل السريع
          flutter build apk --release --no-pub

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-haedirasso@gmail.com
