workflows:
  android-workflow:
    name: ToTV+ Build Fix
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      # سنستخدم نسخة مستقرة تماماً وأقدم قليلاً لضمان الهروب من الخطأ
      flutter: 3.22.2 
      java: 17
    scripts:
      - name: Hard Reset and Clean
        script: | 
          # تنظيف شامل وحذف الكاش الذي قد يحتوي على الملفات المعطوبة
          flutter clean
          flutter pub cache repair
          rm -rf android/.gradle
          rm -rf android/app/build
          
      - name: Generate Core Files
        script: |
          # إعادة إنشاء الملفات الأساسية برمجياً لضمان عدم فقدانها
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          cat <<EOF > android/gradle.properties
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx4G
          EOF

      - name: Install dependencies
        script: | 
          flutter pub get

      - name: Build APK (Force)
        script: | 
          # استخدام apk بدلاً من bundle لأن الـ bundle يمر بمراحل فحص أكثر صرامة
          flutter build apk --release --force

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
