workflows:
  android-workflow:
    name: ToTV+ Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      # تحديد نسخة مستقرة ومحددة لتجنب أخطاء التوافق
      flutter: 3.24.0 
      java: 17
    scripts:
      - name: Clean build cache
        script: | 
          flutter clean
          rm -rf android/.gradle
          rm -f android/local.properties

      - name: Fix missing Gradle files
        script: |
          # إنشاء ملف local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          # إجبار إعدادات AndroidX
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "org.gradle.jvmargs=-Xmx4G" >> android/gradle.properties

      - name: Install dependencies
        script: | 
          flutter pub get

      - name: Build Android APK
        script: | 
          # استخدام build apk بدلاً من bundle لتسهيل التجربة الأولى
          flutter build apk --release --no-pub

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-haedirasso@gmail.com # ضع إيميلك هنا لتستلم الرابط
